<?php
/**
 * Helpers for the new design system.
 */

/**
 * Output a responsive <picture> with WebP source.
 * Looks for sibling WebP files generated by optimize-images.py.
 *
 * Usage:
 *   img('images/main-header.jpg', 'Couple by the sea', ['class' => 'hero-img', 'sizes' => '100vw', 'eager' => true]);
 */
function img($src, $alt = '', $opts = []) {
  $opts = array_merge([
    'class'    => '',
    'sizes'    => null,
    'eager'    => false,
    'attrs'    => [],
    'widths'   => [480, 960, 1600],
  ], $opts);

  $rootRel = '/' . ltrim($src, '/');
  $absFs   = $_SERVER['DOCUMENT_ROOT'] . $rootRel;
  $info    = pathinfo($rootRel);
  $dir     = $info['dirname'];
  $name    = $info['filename'];

  // Build srcset for WebP variants that actually exist on disk
  $webpFull = $dir . '/' . $name . '.webp';
  $srcset = [];
  foreach ($opts['widths'] as $w) {
    $candidate = $dir . '/' . $name . '-' . $w . '.webp';
    $abs = $_SERVER['DOCUMENT_ROOT'] . $candidate;
    if (@file_exists($abs)) {
      $srcset[] = $candidate . ' ' . $w . 'w';
    }
  }
  // Always offer the full-size WebP as a fallback if it exists
  $hasFullWebp = @file_exists($_SERVER['DOCUMENT_ROOT'] . $webpFull);

  $cls    = $opts['class'] ? ' class="' . htmlspecialchars($opts['class']) . '"' : '';
  $loading= $opts['eager'] ? 'eager' : 'lazy';
  $prio   = $opts['eager'] ? ' fetchpriority="high"' : '';
  $decode = ' decoding="async"';
  $sizes  = $opts['sizes'] ? ' sizes="' . htmlspecialchars($opts['sizes']) . '"' : '';
  $extra  = '';
  foreach ($opts['attrs'] as $k => $v) $extra .= ' ' . $k . '="' . htmlspecialchars($v) . '"';
  $altEsc = htmlspecialchars($alt, ENT_QUOTES);

  echo "<picture>";
  if (!empty($srcset)) {
    echo '<source type="image/webp" srcset="' . htmlspecialchars(implode(', ', $srcset)) . '"' . $sizes . '>';
  } elseif ($hasFullWebp) {
    echo '<source type="image/webp" srcset="' . htmlspecialchars($webpFull) . '">';
  }
  echo '<img src="' . htmlspecialchars($rootRel) . '" alt="' . $altEsc . '"' . $cls . ' loading="' . $loading . '"' . $decode . $prio . $extra . '>';
  echo "</picture>";
}
?>
