<?php
require_once __DIR__ . '/partials/helpers.php';
$page_title       = "Reviews | It's A Wonderful Life Weddings";
$page_description = "Here you find reviews of our service, check them out and find out why we are becoming the Metros premiere wedding minister service.";
$page_keywords    = "reviews, comments, pastor, david, barger, thanks, weddings, wedding, ceremony, ceremonies, ceremonial, ministers, minister, cost, price, cheap, inexpensive";
$page_path        = "/reviews.php";
$page_image       = "/images/bride-groom-tree.jpg";

$reviews = [
  ["11/16/2021","Teri H", "We were so fortunate to have Pastor David for our daughter’s wedding. He was an amazing officiant that was easy to talk with, very helpful in guiding our daughter and now son-in-law in planning their ceremony, and was kind in his interaction with our wedding party and guests. His communication skills are excellent which was quite helpful as we changed dates due to the pandemic. His experience in officiating was quite evident in our ceremony and we are quite grateful for his calm, positive demeanor as well as his sense of humor. The most compliments our guests shared with us throughout the wedding day we’re about how much they liked Pastor David."],
  ["11/16/2021","Melissa Z","Elaine was amazing as our officiant! 5 star professionalism and punctuality; would definitely recommend!"],
  ["11/16/2021","Carlos C","Pastor Dave - Highly recommended. Made our day perfect."],
  ["11/02/2021","Anne H","Pastor Joe Hallam was amazing since the day we first spoke. He made sure the ceremony was stress free. Him and is wide coordinated the ceremony from start to end and it was beautiful! I wasn’t sure if my family would understand or if they would even be emotional since English is their second language and we honestly have no regrets! He made the ceremony even more special by making it more personalized. I 1000% recommended to have him officiate your wedding"],
  ["11/01/2021","Heidi N","Pastor Joe was exactly what Greg and I were looking for in an officiant. He was full of wisdom, and humor, and he was encouraging, professional and spiritual all while conducting our ceremony with love and tenderness as if he had known us for many years. We would definitely recommend Pastor Joe and It’s a Wonderful Life Weddings officiants."],
  ["11/01/2021","Christina H","Pastor David was amazing. Our ceremony was short and sweet, the way we wanted it. It did not sound like he was just reading off of a page, he made it sound like he actually knew us! It was very easy to book with him, and he really looks at the little details to make everything special. He took care of sending our marriage license off to the courthouse. We had a few people come to us and ask where we found him because they liked him. I only wish he could have stayed for dinner and some dancing!"],
  ["10/24/2021","Andrea H","We had Pastor Dave officiate our wedding and I couldn't be more thankful for him being a part of our day! I was nervous at first to hire an officiant that didn't know me and my husband but from the very first meeting, Pastor Dave made us feel comfortable and at ease. He was so kind and great to work with. He customized our ceremony to exactly what we wanted and was entertaining during the ceremony. Even my grandmother commented to me at the wedding that she thought he did a great job. I would highly recommend his services."],
  ["10/15/2021","Paola R","I will recommend them to everyone who is looking for an officiant they are responsible and great to work with.. Elaine was great thank you much"],
  ["06/21/2021","Autumn B","Pastor Joe was great! He provided a little bit of comedic relief and levity while still maintaining the seriousness and significance of the ceremony. He gave us the great suggestion to have a wine box ceremony. I can't wait to open our box on our 5th anniversary!"],
  ["06/08/2021","Christine P","Pastor Joe and his wife Glenda are amazing!! David wrote a beautiful ceremony! We got many compliments from our guest on how great Joe was and how great the ceremony was! I am so thankful I was able to find It’s a Wonderful Life Weddings SA!"],
  ["05/26/2021","Lauren H","Pastor Joe Hallam officiated our wedding this May and he is an absolute treasure! We met with him over Facetime a few times before our day and developed a relationship with him so he could get to know my then-Fiance and I and help make the ceremony something special and a reflection of us. Pastor David Barger also was a tremendous help in creating the outline and \"script\" (don't worry - they won't read it word-for-word!) for our ceremony. This helped us ensure our ceremony would be designed exactly as we wanted, ensured that any preferred wording would be used, and so everyone knew what to expect. Sooo helpful! On a personal note, through this process Pastor Joe and his lovely wife Glenda have become very special to us. Though we did hire him to provide an important service to officiate our wedding, in our hearts Pastor Joe and his wife feel more like family to us. Pastor Joe had genuine enthusiasm for us as a couple, for our partnership, and for the life we will build together. His wife proudly accompanied him to our wedding events and kindly took the time to help fluff my dress or move a hair from my face as we posed for photos. It was an honor to have them make our ceremony so special -- it was truly better than we could have imagined. If you are looking for a Pastor who will take the time to know you and your partner, to help guide you as you transition into marriage, to make your ceremony incredibly special, then you must reach out to Pastor Joe and Pastor David! One of my favorite things is that he was able to manage that delicate balance of making the ceremony special and serious, while also being fun, interesting, and getting a few laughs out of us all too! We hope to stay in touch with them in the years to come. Thank you all!"],
  ["posted 05/25/2021","Jerrilyn M","Pastor David Barger was awesome! Very professional, punctual and led the ceremony beautifully."],
  ["05/19/2021","Nellia J","With all the chaos of wedding planning, Pastor David and Ms. Elaine were the calming, reassuring presence we needed. We did the initial meeting via video chat and immediately knew they were the right fit for us. Pastor David provided several ceremony samples and we went through two revisions. He was committed to making sure it was perfect. At the rehearsal, Ms. Elaine provided guidance, suggestions and patiently waited while we practiced as many times as we needed. On wedding day, both Ms. Elaine and Pastor David encouraged and reassured us, continues to guide the process seamlessly. We ABSOLUTELY recommend It's A Wonderful Life Weddings SA!"],
  ["05/19/2021","Scott G","Pastor Dave Barger did a fantastic job with understanding and executing specifically what we wanted to accomplish. Very detailed oriented and timed everything perfectly as a wedding ceremony can be. Very personable and respected in his field. We highly recommend him to any couple ready to take the next step in a life commitment to another."],
  ["05/10/2021","Hali P","Pastor David is wonderful. Although we only had 1 zoom meeting, he spoke as if he had known us forever. Our wedding guests said this same thing to us all night long as well. We are very lucky to have found him through our wedding planner. We couldn’t have asked for a better person to perform our ceremony. You cannot go wrong with choosing him for your special day! Thank you again, Pastor David!"],
  ["05/08/2021","Peyton S","I am very happy we hired Pastor David for our wedding! He was easy to work with and did a wonderful job on the ceremony. He is very flexible on conducting the ceremony however you want it to be, but is also very helpful with making suggestions whenever we weren't sure what we wanted. Definitely one of those vendors that made the day easier and less stressful. I highly recommend!!"],
  ["04/06/2021","Candice F","We first met Pastor Joe at a friend’s wedding in Boerne a couple years ago. I knew then that I wanted Pastor Joe to officiate our ceremony. (we weren’t even engaged yet) We got in touch with him and asked if he would do it, of course he would! We were so very fortunate that he was willing to drive all the way to Crockett from San Antonio. Pastor Joe and Pastor David are extremely pleasant to work with, we are looking forward to having lunch with Pastor Joe sometime when we travel to San Antonio. I recommend their services 1000%!!"],
  ["03/19/2021","Barbie C","Pastor David made me feel like I’ve known him forever. Welcoming and warm. He gave an amazing ceremony for my wedding. I’m not religious but I felt so warm and loved."],
  ["03/07/2021","Gabriel B","David was so helpful in the whole process. We actually forgot to get our marriage due to doing so much at once and thanks to his reminder we avoided any problem with that. The rehearsal was smooth, and the service was just what we wanted from the custom video to the light humor throughout the service. We can’t thank you enough for being a part of our special day!"],
  ["02/23/2021","Miranda B","David did a phenomenal job officiating our wedding despite the unforeseen circumstances of freezing weather. He was easy to get a hold of during the process and was very understanding. I highly recommend Pastor David!"],
  ["11/27/2020","Brooke R","Pastor David was great! He had a wonderful personality and made the ceremony so special. We had many compliments on how perfect the ceremony was."],
  ["11/16/2020","Ashleigh J","Look no further than Pastor David for an officiant for your wedding. From the moment we met him, we clicked and felt completely understood. He guides you through every step of the way and makes your ceremony JUST the way you want it. Our guests loved him as well and we received endless compliments!"],
  ["11/01/2020","Blake B","Pastor David and Pastor Joe were great to work with from start to finish. Both were very easy to contact and worked well with us both to craft our ceremony and vows. Meeting with Pastor Joe and his wife was a helpful one hour together that set the tone for our plans for the wedding and how we wanted the ceremony to go. Their advice and feedback was really helpful, and we appreciated the guidance that they provided. Pastor Joe was great to work with on the day of the ceremony, and we were really happy with our decision to hire he and Pastor David. We would definitely recommend them for wedding events in Central Texas."],
  ["10/05/2020","Taylor C.","WOW- Pastor David was more than we ever could have asked for! Such an easy going man and even off just one FaceTime interview, he nailed it with the rough draft of our ceremony.... the final edition was AMAZING. There wasn’t a dry eye anywhere. He works with you and not only does he have a beautiful ceremony written, he is an EXCELLENT speaker. Beyond that, he even had his wife help with telling us when to walk and coordinate the ceremony!! Love the pastor cam, it gives us an amazing memory to watch in the near and far future. When I say you could not ask for a better officiant, I mean he is the ABSOLUTE BEST and you would be crazy not to have him help you with your wedding!!"],
  ["08/05/2020","Ashley Gale V.","Pastor Joe could not be more wonderful. We will have the honor of having him officiate both a private ceremony on the River and our big to do. He truly takes a genuine pride in doing what he does and it shows!"],
  ["07/26/2020","Kathy L.","What a joy it was to work with Pastor David! He was patient, helpful, thorough, timely, and truly brought life to our service. We could not have asked for a more personal and expressive pastor to marry us. Pastor David, thank you for making our wedding ceremony so special!"],
  ["06/06/2020","Cara C.","We are very blessed to have discovered It’s a Wonderful Life Weddings SA with Pastor David. Our ceremony service was nothing but perfect and fit our personality well. We thought the process was very comfortable and result absolutely amazing. Nothing but wonderful praises from all that were present or view the lapel cam video. I loved watching our wedding from that perspective. We highly recommend and very happy that we discovered. Pastor David that you for everything!!"],
  ["05/01/2020","Justin S.","Pastor Dave is a true blessing. From the moment we met him we knew that he would be able to help us make our wedding the most perfect day of our lives. He is kind and witty and a professional in every way. He understands what couples are dealing with leading up to the wedding day and he is a cool calm relaxing voice of reason and reassurance. He met with us several times and is available both in person and via the web. We met with him both ways and enjoyed our conversations getting to know him, and allowing him to get to know us. He is able to prepare a wonderful service that he custom creates just for your relationship and for your wedding day. We actually had to postpone our celebration due to the shelter in place order, but Pastor Dave did not let that deter him. When we asked him to officiate our wedding while observing the social distancing and small group with only our immediate family present, he jumped at the opportunity. He truly loves what he does and bringing couples and families together. Thank you Pastor Dave, and we look forward to seeing you at the next wedding where we celebrate with our whole family and friends!"],
  ["03/20/2020","Ryan R.","At first, my wife (love using that term now) and I were considering a family member or friend to be our officiant - but when we couldn't decide on one person, our wedding planner suggested we hire a professional service. We read the good reviews and eventually opted to have a video-chat consultation with Pastor David Barger, where he wanted to know more about us and listened to us give our expectations. There was no pressure to make a decision, but after the chat we already knew we had to have him by our side! David was very professional and had a first draft of our ceremony within 48 hours! The rehearsal was smooth and the actual ceremony was spot-on! His choice of words, the selected readings, and the way he worked the crowd were fantastic! Lastly, we were provided a body-cam footage of the entire ceremony! We did not hire a videographer so this was a pleasant surprise to cherish forever! Thank you Pastor David for your services!"],
  ["03/20/2020","Laura F.","David was amazing! He made our wedding day perfect and I can not recommend him enough. Our wedding would not have been complete without him. He’s the best!"],
  ["12/18/2019","Michelle L.","Pastor Joe was so sweet and patient with us when we changed our mind 50 times. He helped us get all the final details settled, which was awesome because we really had NO IDEA what we were doing. My wedding certainly wouldn't have gone nearly as smooth without all his help."],
  ["12/03/2019","Kendra F.","Pastor Joe did a wonderful job officiating our wedding! We worked with Pastor David on our ceremony script and made it into exactly what we wanted. Pastor Joe added in a few recommendations during the ceremony which we were happy with, even though he made them “surprises” which worried us a tad. The ceremony was beautiful and we received many compliments!"],
  ["11/12/2019","Andria C.","Pastor David was great and easy to work with. We made last minute changes to our ceremony and without hesitation he made those changes for us. With all the wedding planning we almost forgot to get our marriage license (which is the important thing) and Pastor David reminded us. He was at the rehearsal and wedding on time and everyone loved him during the ceremony!"],
  ["11/02/2019","Jieun H.","The officiant went above and beyond to ensure that we were comfortable and happy with the script. We passed around multiple drafts to each other, and they were able to accommodate some of our last minute changes. Elaine was the officiant for our wedding, and she officiated us beautifully. The couple was so understanding of our circumstances with some sick family members, and took extra steps to ensure that they were recognized. They're such a caring and wonderful couple that goes the extra mile for the couples. I highly recommend them!"],
  ["10/29/2019","Kelsey B.","Pastor David was absolutely amazing as our officiant. He incorporated just the right amount of humor and seriousness. And as a person, he is just as wonderful - no pun intended. He was also very flexible when I made last minute changes, which brought me relief. Hopefully, I will never have the need for an officiant again but when any of my friends are looking for one, I will be sure to recommend Pastor David Barger. Our ceremony was outstanding, thanks to him!"],
  ["10/22/2019","Kimberly B.","After reading all of the reviews we selected pastor David to officiate our wedding and we are so glad we did!  He was helpful in showing us examples of ceremony speeches making it so easy for us to figure everything out. He was easy to contact with any concerns or questions and he was easy for payment as well. During the ceremony he had actually recorded it through a little pocket camera of some sort! I loved that. It was personal and it didn’t feel like it was scripted or he was just there to do the ceremony and then leave. David was amazing and definitely pulled our beautiful unforgettable day together. I recommend Pastor David for sure! You won't be disappointed!"],
  ["10/20/2019","Alma D.","We are so happy that Pastor David officiated our wedding! He helped us to create the perfect ceremony! Pastor David and his lovely wife Elaine came to our house to meet with us and he listened to our expectations. Soon after that he sent us a template to help personalize our ceremony. He worked diligently to make sure that our ceremony was exactly what we wanted. He even came by the night before the wedding to give us a quick briefing and make sure we felt good about the whole process. His orchestration of the wedding was impeccable! Thank you for the \"Wonderful Life Wedding\"! Truly beautiful, always memorable!"],
  ["10/14/2019","Nichole B.","Wow. Where can I get started with Pastor David Barger? My husband Michael and I were married this past Saturday in Dripping Springs. Pastor David is a clear and consistent communicator, calm and dependable, and very experienced with how to run a successful ceremony experience. Exactly what you want in an officiant. Michael and I planned our wedding from out of state, and David would meet with us regularly via Skype to ensure a personalized and successful ceremony. He worked with us to identify readings, created a script for our unity braid, and kept our audience engaged for a 30 minute ceremony. We have loved working with him before, during and after our wedding. Beyond highly recommended, we wouldn’t have wanted our wedding with anyone else!"],
  ["10/10/2019","Mercedes G.","Pastor David was the absolute best choice to officiate our wedding. He made everything specific to us and allowed us to review and choose what we wanted in our ceremony. I did not want a drawn out or heavily religious ceremony for our wedding and he provided the perfect balance for us. He was very quick to answer all of our questions compared to others we reached out to. His personality came out during the readings in our ceremony and made the whole process much more memorable and fun. Thank you so much for everything Pastor David!"],
  ["10/08/2019","Deana C.","Absolutely wonderful. One of the best decisions we made for our wedding. This is an extremely important part of the day and something your guests take notice of."],
  ["10/01/2019","Jacob B.","Pastor David was a great officiant and even better person. He was good with the crowd, gives you specific attention, and most importantly gets you married. The experience began with an interview where you feel a genuine passion for happiness and love resonating from Pastor David. His questions are not just to get to know you, but to enter your life and create a message that's personal to your individual relationship. Pastor David will give you exactly what you need no matter what!"],
  ["09/06/2019","Molly P.","Pastor David Barger was an answer to prayer!!! The ceremony he performed was so special, personal and such a perfect beginning for a marriage!"],
  ["08/24/2019","Caroline P.","David was fabulous! He met with the two of us on skype as we were too far from him to meet in person. He learned about us after giving us a synopsis of the services he provides. He quickly wrote up the ceremony and emailed it to us for our input. We gave him some changes to make and he did quickly. David got to the wedding site early. He was extremely friendly and professional. We were both happy with his service. The bonus was getting a video of the ceremony from him taken via a camera in his pocket. We highly recommend David and his company."],
  ["08/22/2019","Jennifer A.","Super easy to work with! Personalized ceremony that fit us as a couple. Same sex friendly."],
  ["07/02/2019","Carla S.","What a wonderful experience it was to have Pastor David Barger marry us! He and his wife were both really sincere and made us feel welcomed in their home. We even brought along our little dog for our ceremony! Pastor Barger took the time to go over the different ceremonies and answered any questions or concerns we had. Our ceremony was beautiful and we all enjoyed cake afterwards. We highly recommend Pastor Barger with What A Wonderful Life to marry couples."],
  ["06/21/2019","Kim D.","Pastor David was the perfect officiant for our wedding! He took time to get to know my husband and I both individually and as a couple. He personalized our vows and told a beautiful story of our relationship. You can’t go wrong with Pastor David and It’s a Wonderful Life Weddings!"],
  ["06/10/2019","Carina O.","David Barger from It's a Wonderful Life Weddings was the PERFECT person to officiate our wedding. He was kind, sincere, and respectful to our denomination practices. He was very particular in discovering more about my Husband and I to ensure he expressed our story in true detail. He was easy to contact, quick to respond, and supportive of our choices for the details of the ceremony. He is a gem! We couldn't have been more thankful to have found Pastor David! Thank you for the most wonderful experience!!"],
  ["06/06/2019","Jessica H.","Our wedding ceremony couldn’t have been more perfect. I was a little hesitant about finding an officiant for our wedding, especially one I didn’t know previously, but our first conversation with Pastor Joe eased all of those concerns. He really took the time to get to know my fiancé and me and it definitely showed during the ceremony. It was absolutely beautiful and exactly what we wanted. I would recommend It’s a Wonderful Life Weddings to anyone looking for an officiant! Pastor Joe and Pastor David are fantastic and put so much thought and care into each ceremony. Thank you again for everything!"],
  ["06/05/2019","Jeremiah B.","David Barger and Elaine Hanson are close family friends and David officiated both of my sibling's weddings. It was a complete privilege and honor to have him officiate our wedding. David was very knowledgeable, thorough, and technologically proficient. We were able to coordinate much of the initial planning via Skype and through sharing documents on Google Drive since we were planning a destination wedding in San Antonio from Kansas City. David and Elaine were prompt and well prepared to coordinate our rehearsal the day before the wedding and arrived early on the day of our wedding to help with setup and preparation for the ceremony. David has a natural charisma that is undeniable, a quick wit, infectious humor, and a genuine concern and care for his clients. Elaine was so kind, flexible, insightful, and willing to assist with anything that we needed during the frenzy of wedding preparation. David also instructed us on how to visit the courthouse and obtain all the proper legal documentation required and met with us a few days before the wedding and rehearsal to ensure that the ceremony was completely customized to our liking. We were even able to make some last minute tweaks the day before after reflecting on the prior meetings and decision-making. There is a reason It's a Wonderful Life Weddings is voted the best officiants in San Antonio, they are truly meant to be doing this type of work and we couldn't have asked for a better outcome. David even recorded the entire ceremony via his signature Pastor Cam and had it uploaded to a private YouTube link by the next day! We are forever grateful for the amazing services that were provided to us on and leading up to this very special day. We were so comfortable and things went so smoothly because of all the preparation and attention to detail. Thank you David and Elaine for all your hard work, your true friendship, and your investment in our lives. We love you guys so very much!"],
  ["05/13/2019","Alex K.","My wife and I cannot say enough great things about Pastor David Barger. He was very professional, organized, and responsive. He far exceeded our expectations and always went above and beyond to answer our questions and provide suggestions. Our ceremony went exactly as planned and was amazing. We definitely recommend Pastor David Barger for your officiant needs."],
  ["04/23/2019","Ursula R.","I had the best experience working Elaine and David. They are extremely professional, flexible, couple focused, and are two genuinely people who care about getting to know you as a couple to deliver exactly the ceremony you want! Out of all the vendors I had to deal with for our wedding, David and Elaine were like a breath of fresh of air! They are hands down the best!"],
  ["04/07/2019","Madison S.","Pastor David and his wife were very welcoming at our first meeting with them! There were beyond helpful throughout this whole process! They gave us all the material and steps on what to do, how to do it, and when it should be done to ensure we weren't running around crazy last minute. We would highly recommend them! The ceremony was perfect!"],
  ["03/12/2019","Meagan L.","Pastor David’s service was so amazing and so personal! I couldn’t have been happier with our ceremony and he even surprised us with a special, intimate video of the ceremony from his perspective. How wonderful!! I’d highly recommend him for your wedding if you’re looking!"],
  ["01/07/2019","Glenn R.","Pastor Barger did a wonderful job throughout the entire process and I would recommend him to anyone 10/10."],
  ["12/10/2018","Holli M.","For those couples that are not using a friend or loved one as an officiant, Pastor Dave is a wonderful option for your wedding! Right from the get-go, he was easy to talk to and work with. Military/First-responder friendly company. Never felt like he was too busy to go over our ceremony or answer questions that we had. The Pastor-Cam recording of our wedding was ultimately a nice addition to our memories that he provided free of charge. He is personally a very friendly and easy-going individual and can offer a very pleasant addition to any wedding or formal ceremony. We feel very fortunate to have found Pastor Dave, definitely recommend him for your officiant needs."],
  ["11/22/2018","Alyssa R.","Pastor David was amazing, he really took time to know us and understand what we wanted. He answered any questions we had, and was great through me changing my mind more than a few times lol. After the ceremony everyone told me how much they loved him!"],
  ["11/19/2018","Amanda C.","Pastor David and Elaine were both wonderful in planning and performing our ceremony. Although Pastor David could not perform the wedding himself, due to a double scheduling, he had his wife step in and officiate the ceremony for us. They were both very accommodating and willing to make any changes that we wanted."],
  ["11/18/2018","Sarah O.","David was amazing really took into account what we wanted in a wedding! So perfect!!"],
  ["11/07/2018","Mark F.","My new wife and I had looked around for awhile to find a pastor to perform our ceremony. When we first met with Pastor David, and his wife in their beautiful home, they welcomed us graciously and made us feel comfortable and, at home. They took the time to get to know us, to understand what this day meant to us, and what he created in the ceremony was perfect. The highlight of the entire experience was a couple of days later, when I was asked by a guest at our wedding who the pastor was and they commented: \"He (Pastor David) seemed like he really wanted to marry you two, it was almost like he was just as proud to be there as you and your wife\". I could not have described him any better. Thank you, Pastor David, for making our day even more special."],
  ["10/31/2018","Sami F.","They were warm, caring, and compassionate and to went the extra mile to ensure everything was perfect. Provided constructive tools to ensure a Christian marriage during the planning and after wedding day. Highly recommended to everyone."],
  ["10/31/2018","Melanie O.","Elaine was great! They put together a beautiful speech with minimal to no input from us. They were the first ones to show up at the rehearsal dinner to go over important details with us. They were also one of the first vendors there the day of the wedding. We were glad to have them be a part of our special day and we know you will too!"],
  ["10/30/2018","Elizabeth D.","Pastor David Barger was professional, organized, detailed, prompt and went above and beyond. When we first met him we were so comfortable and definitely confident we wanted him to officiate our wedding. Our ceremony was the most important part of the wedding and he exceeded our expectations with giving us direction, options, suggestions, immediately responding to our emails/calls and taking time to read our vows. Our wedding was on 10/20/2018 today is 10/30/2018 and we are still getting compliments from our family and friends about Pastor David and how engaged he was during the ceremony. I stated, “he went above and beyond” well the next day he had something very dear and special for us. I won’t reveal what this was so he will have an opportunity to bring joy to another happily married couple. If you are searching for an officiant you can stop searching because you have found the best!!! Pastor David Barger I would like to thank you for a beautiful and memorable wedding ceremony."],
  ["10/30/2018","Justine C.","Pastor David is amazing. His super friendly and helpful. He really made our ceremony special. We had a Disney theme wedding and he put a little bit of Disney in our ceremony. The ceremony was short and sweet, just the way we wanted. AMAZING! you cannot go wrong with him."],
  ["10/24/2018","Elizabeth B.","David and Elaine were so thoughtful and professional. They were both a joy to work with, and helped make our day that much more special. Thank you again, David and Elaine!!!"],
  ["10/23/2018","Gavin W.","Pastor Joe and the team were more than helpful in so many ways. They catered to our every need including writing a custom ceremony after getting to know us over dinner, they included keyboard + pianist for the ceremony, they even went so far as to offer assistance in tracking down a translator for a bi-lingual ceremony. Service was above and beyond! And what’s more is they actually cared about our marriage. I couldn’t imagine lending a better recommendation to any wedding official/priest/pastor."],
  ["10/19/2018","Jennifer A.","I am so thankful to have had David marry us. He has a wonderful sense of humor and made our ceremony personal, intimate and light. He took care of us on rehearsal day and walked everyone through how they were supposed to walk in as well as the handling of the marriage certificate. He also had a go pro in his pocket day of the ceremony and recorded the whole ceremony. We are forever grateful for our Pastor and highly recommend!!"],
  ["10/18/2018","Rachel W.","David Barger was phenomenal! He made our wedding day truly special. He listened to our ideas and values and customized our perfect intimate ceremony just they way we envisioned it. I am still getting compliments about the wedding ceremony and his beautiful words 3 months later! I would highly recommend David Barger to perform your wedding ceremony!!!"],
  ["10/05/2018","Kathryn M.","Pastor Dave was awesome! He worked with me to make sure we had all of the little details for the ceremony just right and made sure everything went smoothly the day of! I would definitely recommend It's a Wonderful Life Weddings, specifically Pastor Dave!"],
  ["09/08/2018","Alondra G.","Pastor David was incredible! He first talked to us to get to know us a bit and then worked with us to create a custom ceremony that reflected our style, personality and relationship. He always responded to my emails promptly and was very flexible with our requests. He showed up early to the rehearsal and the wedding to ensure he had time to get what he needed for our ceremony without having to come to us with last minute questions which I truly appreciated. His actual delivery of the ceremony was perfect and he was always very professional. Extra points for delivering our ceremony in 98 degree weather. I would 100% recommend Pastor David, he will make your ceremony truly beautiful and special."],
  ["09/06/2018","Elizabeth C.","Pastor David was amazing! He was at our venue an hour before the ceremony to 1.) assure me it would be okay , 2.) meet with our photographers to discuss details, and 3.) get our witnesses to sign our marriage license. We met with him and his wife to discuss what type of ceremony we wanted and he kept in contact prior to the ceremony to get just the right words down. He did not disappoint! The ceremony was absolutely BEAUTIFUL. Perfect. His words were quite moving with a touch of humor. If you're getting married in San Antonio, Texas, I HIGHLY recommend Pastor Dave. You will NOT be disappointed."],
  ["07/19/2018","Patrick V.","I'm a wedding vendor myself, so I have seen many different officiants. The first thing I noticed about Pastor David is his friendliness and professionalism. What really showed me how good he is was when he arrived on the day of the wedding. Many other officiants require a certain amount of assistance in finding out where they need to set up. However, Pastor David already knew to speak with the DJ to get a lapel mic, knew where to stand for the ceremony, and had a very confident/welcoming atmosphere during the ceremony. He even comes with a \"pastor cam\" which he uses to record the wedding for us at no additional charge!! Honestly I was amazed that he included so much value at such an affordable price. I know how hard it can be to find decent reviews so I'm making sure David gets the love he deserves!"],
  ["06/19/2018","Ashton T","Pastor David did such an amazing job officiating our wedding and I can't say enough great things about him! When we met him, both David and his wife immediately made us feel comfortable. He let us decide how we wanted to do our ceremony and gave us a couple rough drafts until the wording was just the way we wanted it. He also gave us advice on how to write our own vows. He is easy to communicate with and made our ceremony everything I had hoped i would be. We received several compliments on how great our officiant was after the wedding. I can't recommend him enough!!"],
  ["06/18/2018","Raven R.","My husband and I couldn't have asked for a better officiant for our wedding. Pastor Joe took two hours to sit down with us over coffee and pastries with his wonderful wife and just talk about our lives and what we'd like our wedding to look like. He was accommodating and kind throughout the entire process. The ceremony was the perfectly personal and meaningful, and everyone commented how lovely the ceremony was at the reception. We would recommend Pastor Joe to anyone looking for someone to officiate their wedding."],
  ["06/10/2018","Priscilla R.","David was so helpful. We felt 100% comfortable from the moment we sat down with him to share our story. He was willing to change our ceremony outline multiple times to ensure that it matched our style. During the rehearsal, David and his wife made us feel so comfortable. He was very nice to our families and wedding party. He even made a last minute change to make sure that all our family was included. David followed through on our wedding day and we received many compliments from our guests about how beautiful our ceremony was. I highly recommend that you choose It's a Wonderful Life Weddings SA!"],
  ["05/29/2018","Ben S.","Pastor Dave made my husband and I feel very comfortable from the first time we met with him and his wife. We wanted someone who would mix my Christian background with that of my husbands more agnostic beliefs. What he came up with was perfect. He took the time to get to know our personal story and was so helpful with our questions and efficient in coming up with our marriage ceremony months ahead of time. Having the most important part of the day taken care of really helped us feel relieved and also kept us focused on the direction we wanted our special day to take. Thank you, Pastor Dave, for creating our perfect ceremony!"],
  ["05/13/2018","Amber P.","Pastor David was so nice and really did a great job with our ceremony. He worked with us to customize everything just the way we wanted. Guests commented all night on what a enjoyable ceremony it was and they liked that he made us laugh."],
  ["04/30/2018","Monica P.","Finding an officiant to marry us was one of the hardest task in the wedding planning process. I stumbled upon It's a Wonderful Life Weddings SA through The Knot and felt absolute joy from the initial conversation I had with David. My hunny and I met with him and his lovely wife Elaine for a consultation and we knew instantly he was the one to marry us! They are both full of happiness, love and have a great sense of humor. David made changes to our ceremony script days before the wedding without hesitation even after I had approved it. During our rehearsal David was very patient, thorough and provided great feedback so that we could have a flawless ceremony. His wife Elaine was THE BEST in guiding our wedding party down the aisle. I felt no worry at the beginning of the ceremony and as a bride this was the best feeling. I was able to just concentrate on myself and getting down the aisle. I felt like we got so much more than we expected considering the price we paid. His pastor cam is awesome! We are so grateful to have had the pleasure to meet these beautiful people and have David marry us. My guest absolutely loved him! From the bottom of our hearts, thank you David and Elaine. Love always, The Ganoes."],
  ["04/29/2018","Hannah C.","Pastor David is so great and I would recommend him to anyone. He is genuine, easy to work with, and has a wonderful calming and cheery personality. He met with us almost a year out from our wedding since it was the only time we would be in town, and again on a visit right before the wedding. He really gets to know you (but is a nice balance- quickly gets down to the task at hand too) and helped us create a personalized ceremony that perfectly fit us and our families. This, for us, was \"religion light\" but still very meaningful. He was easy to keep in touch with throughout the process. He made everything easy, from running our rehearsal dinner... down to the detail of sending in our marriage license in. Thank you for getting us married!"],
];

// Schema: aggregateRating + a handful of recent Review entries
$reviewItems = array_slice($reviews, 0, 10);
$page_schema = [
  "@type" => "ReviewPage",
  "name"  => "Reviews of It's A Wonderful Life Weddings",
  "review" => array_map(function($r) {
    return [
      "@type" => "Review",
      "author" => ["@type" => "Person", "name" => $r[1]],
      "datePublished" => preg_match('#(\d{2})/(\d{2})/(\d{4})#', $r[0], $m) ? "$m[3]-$m[1]-$m[2]" : null,
      "reviewBody" => $r[2],
      "reviewRating" => ["@type" => "Rating", "ratingValue" => "5", "bestRating" => "5"],
      "itemReviewed" => ["@id" => "https://www.itsawonderfullifeweddings.com#organization"]
    ];
  }, $reviewItems)
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include __DIR__ . '/partials/head.php'; ?>
</head>
<body>
<?php include __DIR__ . '/header.php'; ?>

<main id="main" tabindex="-1">

  <section class="subhero">
    <div class="subhero-bg">
      <?php img('images/bride-groom-tree.jpg', 'Bride and groom by a tree', ['eager' => true, 'sizes' => '100vw']); ?>
    </div>
    <div class="subhero-inner" data-reveal>
      <nav class="crumbs" aria-label="Breadcrumb"><a href="/index.php">Home</a><span class="sep">/</span>Reviews</nav>
      <div style="color: var(--gold-soft); letter-spacing: 0.2em; font-size: 1.2rem; margin-bottom: var(--sp-3);">★ ★ ★ ★ ★</div>
      <h1>Five Star Reviews</h1>
    </div>
  </section>

  <section class="section section--cream">
    <div class="container">
      <div class="grid" style="grid-template-columns: 1fr; gap: var(--sp-5);" data-reveal>
        <?php foreach ($reviews as $idx => $r): ?>
          <article class="testimonial" data-reveal data-reveal-delay="<?= $idx % 4 ?>">
            <p class="testimonial-quote"><?= htmlspecialchars($r[2]) ?></p>
            <p class="testimonial-author"><?= htmlspecialchars($r[1]) ?>
              <span style="margin-left: auto; font-family: var(--f-body); font-weight: 400; letter-spacing: 0.06em; text-transform: none; color: var(--muted); font-size: 0.78rem;"><?= htmlspecialchars($r[0]) ?></span>
            </p>
          </article>
        <?php endforeach; ?>
      </div>

      <div class="text-center" style="margin-top: var(--sp-7);" data-reveal>
        <p class="lede">Ready to be our next five-star story?</p>
        <a class="btn btn--gold" href="/contact.php">Start the Conversation</a>
      </div>
    </div>
  </section>

</main>

<?php include __DIR__ . '/footer.php'; ?>
</body>
</html>
